### ISSUE TITLE
The file '/assets/maps/level/level.collection' could not be found.

### ISSUE THREAD

**Issue by gerroon** [astrochili/defold-trenchfold#10]
Hi

Thanks for the example, having issue with Defold 1.6.3

`/example/main.collection The file '/assets/maps/level/level.collection' could not be found.`

**Comment by astrochili** [comment]
Hi

Please follow the [Running the example section](https://github.com/astrochili/defold-trenchfold#running-the-example). The example is about exporting, not about game.
